### PR TITLE
改成使用scss

### PR DESCRIPTION
**Pull request by wi1d5ky**
改用 scss 撰寫 css

### CODE REVIEW

**Comment by kidwm** [comment]
style.css 的檔名不用改吧

**Comment by wi1d5ky** [comment]
我有更新囉！在麻煩你晚點有空時幫我看了 :)
<code>@extend</code> 的用法我是看這篇文章學的：http://tldrify.com/56i

**Comment by kidwm** [comment]
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#extend
> If the two sequences do share some selectors, then those selectors will be merged together and only the differences (if any still exist) will alternate. In this example, both sequences contain the id #admin, so the resulting selectors will merge those two ids:

原來在同樣的條件下會自動合併。

**Comment by kidwm** [comment]
Merged.

**Comment by wi1d5ky** [comment]
Wow, @kidwm 原來你都直接去翻文件

感謝 merge !!

**Pull request closed without merging**
