### PR TITLE
Html compress

### PR DESCRIPTION
**Pull request by PeterDaveHello**
use [jekyll-compress-html](https://github.com/penibelst/jekyll-compress-html/releases) v3.0.2(current latest version) to minify html output.

Use homepage(`index.html`), `about`, `development`, `download`, `news` and `projects` pages as example.

Uncompressed size of the sum:
- 29460 bytes

Compressed size of the sum:
- 26961 bytes

Save about 10% size, can help speed up the loading time.

```bash
-rw-r--r-- 1 peter peter 7192 Mar 11 19:54 about_compressed.html
-rw-r--r-- 1 peter peter 8277 Mar 11 20:00 about.html
-rw-r--r-- 1 peter peter 4035 Mar 11 19:54 development_compressed.html
-rw-r--r-- 1 peter peter 4267 Mar 11 20:00 development.html
-rw-r--r-- 1 peter peter 3793 Mar 11 19:54 download_compressed.html
-rw-r--r-- 1 peter peter 4003 Mar 11 20:00 download.html
-rw-r--r-- 1 peter peter 3399 Mar 11 19:54 index_compressed.html
-rw-r--r-- 1 peter peter 3550 Mar 11 20:00 index.html
-rw-r--r-- 1 peter peter 6809 Mar 11 19:54 news_compressed.html
-rw-r--r-- 1 peter peter 7465 Mar 11 20:00 news.html
-rw-r--r-- 1 peter peter 1729 Mar 11 19:54 projects_compressed.html
-rw-r--r-- 1 peter peter 1898 Mar 11 20:00 projects.html

```

### CODE REVIEW

**Comment by kidwm** [comment]
Github Pages does not support this plugin.
https://pages.github.com/versions/

And I think that gzip deflate is good enough for this site.

**Comment by PeterDaveHello** [comment]
Oops, sorry that didn't notice it's hosted on GitHub page, I'll take a look at it.

**Comment by PeterDaveHello** [comment]
@kidwm how do we know that GitHub doesn't support it? Do you mean jekyll-compress-html is not listed on the list? Thanks.

**Comment by kidwm** [comment]
@PeterDaveHello https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

**Comment by PeterDaveHello** [comment]
Thank you again @kidwm

**Comment by PeterDaveHello** [comment]
@kidwm https://peterdavehello.github.io/chewing.github.com/

Looks it works well, doesn't it?

**Comment by PeterDaveHello** [comment]
https://github.com/PeterDaveHello/chewing.github.com/tree/gh-pages
https://github.com/PeterDaveHello/chewing.github.com/commits/html-compress

**Comment by kidwm** [comment]
@PeterDaveHello you can check the results of them, the file size of chewing.im is a little smaller.

**Comment by PeterDaveHello** [comment]
Okay, just make sure it works in fact.

**Pull request closed without merging**
